### ISSUE TITLE
cannot start "elizagen/doctor_bbn_lisp_1966/bbnlisp.pl" :  unbound symbol: stop

### ISSUE THREAD

**Issue by knbknb** [jeffshrager/elizagen#10]
calling 
`bbnlisp.pl -doctor66 -load bbnlib66.lisp -load doctor.ascii -load scrip.ascii`

yields a very long error message, 
```
    > unbound symbol: stop
    throw was error at ./bbnlisp.pl line 1469, <LOADFILE> line 323.
    throw was error at ./bbnlisp.pl line 1469, <LOADFILE> line 726.

```
Or rather it is a warning.
I can remove the respective lines in the file (they are the last lines just containing "stop"), then the error messages disappear. I get a REPL prompt, I *can* type `(doctor)` and the program responds with  `"tell me your troubles. please terminate input with an enter."`.

The perl I'm using is 
```
This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-gnu-thread-multi
(with 68 registered patches, see perl -V for more detail)
```
on Ubuntu 16.04.4 LTS

**Comment by jeffshrager** [comment]
Thanks for the report. Unfortunately, this is unsupported code. You could contact the author directly, but he isn't subscribed to this repo as far as I know.
